--liquibase formatted sql
--changeset dmuszynski:3
CREATE TABLE USER_AUTHORITY
(
    user_id      BIGINT NOT NULL,
    authority_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, authority_id)
);

ALTER TABLE USER_AUTHORITY
    ADD CONSTRAINT FOREIGN_KEY_USER_AUTHORITY_USER FOREIGN KEY (user_id) REFERENCES USER (id);
ALTER TABLE USER_AUTHORITY
    ADD CONSTRAINT FOREIGN_KEY_USER_AUTHORITY_AUTHORITY FOREIGN KEY (authority_id) REFERENCES AUTHORITY (id);